apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-broker
  labels:
    app: mqtt-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-broker
  template:
    metadata:
      labels:
        app: mqtt-broker
      namespace: azure-iot-operations 
    spec:
      containers:
        - name: mqtt-broker
          image: cesicontainerregistry.azurecr.io/mymqtt-broker:v1
          command: ["sh", "-c", "sleep infinity"]
      imagePullSecrets:
        - name: cesiregistrycred