apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    trust.cert-manager.io/hash: 395a463dd1d5abf5d6f95defc63ace70cf5ccdbd8d8d3589876d285a81ad1255
  creationTimestamp: "2024-10-08T21:54:11Z"
  labels:
    trust.cert-manager.io/bundle: azure-iot-operations-aio-ca-trust-bundle
  name: azure-iot-operations-aio-ca-trust-bundle
  namespace: cesi
  ownerReferences:
  - apiVersion: trust.cert-manager.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Bundle
    name: azure-iot-operations-aio-ca-trust-bundle
    uid: df6f7ce7-411f-4acc-8798-98442c0e5d1d
  resourceVersion: "7625"
  uid: a834ef99-f1b1-4881-aa74-76907be61745
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDgzCCAmugAwIBAgIRAO8+BRUIjj4aMfLeMajSA9owDQYJKoZIhvcNAQELBQAw
    WzESMBAGA1UEChMJTWljcm9zb2Z0MUUwQwYDVQQDEzxBenVyZSBJb1QgT3BlcmF0
    aW9ucyBRdWlja3N0YXJ0IFJvb3QgQ0EgLSBOb3QgZm9yIFByb2R1Y3Rpb24wHhcN
    MjQxMDA4MjE1NDExWhcNMjUxMDA4MjE1NDExWjBbMRIwEAYDVQQKEwlNaWNyb3Nv
    ZnQxRTBDBgNVBAMTPEF6dXJlIElvVCBPcGVyYXRpb25zIFF1aWNrc3RhcnQgUm9v
    dCBDQSAtIE5vdCBmb3IgUHJvZHVjdGlvbjCCASIwDQYJKoZIhvcNAQEBBQADggEP
    ADCCAQoCggEBANVsbLd91E0Zj4ir60n/l26xWLHMjYsbiMkO8Od/aEYvcSskfMGi
    qJNjqIF6h7MwL5zZuRgdeTf5dAlw3Ao7R6IArfmLsvTRJVMbQjoKRfU3CnP9rXrT
    n2SRJ5Bk9sUNKj06n4nS14vkm6PKKS3YUu7wOdbm2lPVl9LhNNiDXPR1eyKMYEZ2
    z/9fy/sfvOSPPFDe+FYfhHleonglb65KRoDzIlOhAgv0RUJKhCPfKdEmUW5W3gHW
    Dk+GsOn8jy+77DSqKAr8r8yfz92uXb1fQpPMCh9BhlGTF+75c0ZHw87gbeD78wM2
    bWGwE3CYYsPcjIGe4LoB2qAsoyqhvkgnPaECAwEAAaNCMEAwDgYDVR0PAQH/BAQD
    AgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFBqkN52NCkHMZgnPHKrXypfK
    ee5uMA0GCSqGSIb3DQEBCwUAA4IBAQCc1+H3uyO69rTOPltM1eCkBTuxCKl0gh3B
    FdJWWDcRsuxk5S1L7FWHXfy6IRVbsvOlVKv+K/NhwhsxHcYeVHLOv684JyojErRy
    NeGhSLeNKyH02r2L9xsob9ZaUsAPW7+8SSCudVZYWtnV7AlhhdEJEsNjWGI+BVlq
    Q0NnOVONoMwqqoziXNMdWa/ovqiKdvYGKyJwl2YbDnu6+MHlqSXA6JOHD9xDu6qt
    S1snwGOj5kJD4dc2vASe8IV/9Z4AvuRlAhOR1nHRy0c2MazxachS2pIk71XSqRwk
    JTgTuHQ6vvkMXhkGXmKf9m+5+ldVAs0PZvIIM87m1mQ37wytDvPC
    -----END CERTIFICATE-----
