apiVersion: apps/v1
kind: Deployment
metadata:
  name: cesi-mqtt-client
  labels:
    app: mqtt-client
  namespace: cesi # Move the namespace here
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-client
  template:
    metadata:
      labels:
        app: mqtt-client
    spec:
      serviceAccountName: cesi-mqtt-client
      containers:
      - name: mqtt-client
        image: cesicontainerregistry.azurecr.io/mqtt-client
        command: ["sh", "-c", "sleep infinity"]
        volumeMounts:
        - name: mq-sat
          mountPath: /var/run/secrets/tokens
        - name: trust-bundle
          mountPath: /var/run/certs
      volumes:
      - name: mq-sat
        projected:
          sources:
          - serviceAccountToken:
              path: mq-sat
              audience: aio-internal # Must match audience in BrokerAuthentication
              expirationSeconds: 86400
      - name: trust-bundle
        configMap:
          name: azure-iot-operations-aio-ca-trust-bundle # Default root CA cert